data:
  csv_dir: data
  max_len: 16
  batch_size: 256
  num_workers: 0
  use_section: true
  use_country: true
  use_timegap: false
  age_bins:
  - 18
  - 25
  - 30
  - 35
  - 40
  - 45
  - 50
  - 55
  - 60
  - 66
  - 200
  label_order:
  - too small
  - fit
  - too large
  - not applicable
model:
  type: transformer
  d_model: 256
  n_layers: 4
  n_heads: 4
  dropout: 0.1
  use_cls: false
train:
  epochs: 30
  lr: 0.001
  weight_decay: 0.01
  betas:
  - 0.9
  - 0.999
  label_smoothing: 0.0
  class_weights: null
  grad_clip: 1.0
  amp: true
  early_stopping_patience: 5
  seed: 1
logging:
  out_dir: artifacts/runs
  write_preds: true
  profile_after_train: true
  topk: 3
  tag: tf_len16_small_s1
