data:
  csv_dir: data
  use_section: true
  use_country: true
  age_bins:
  - 18
  - 25
  - 30
  - 35
  - 40
  - 45
  - 50
  - 60
  - 200
  label_order:
  - too small
  - fit
  - too large
  - not applicable
  max_len: 16
  batch_size: 256
  num_workers: 0
model:
  type: xlstm
  d_model: 256
  n_layers: 4
  n_heads: 4
  dropout: 0.1
  use_cls: false
train:
  seed: 1
  lr: 0.0003
  weight_decay: 0.01
  betas:
  - 0.9
  - 0.999
  epochs: 20
  early_stopping_patience: 5
  amp: true
  grad_clip: 1.0
  label_smoothing: 0.0
logging:
  out_dir: artifacts/runs
  write_preds: true
  tag: xlstm_len16_small_s1
