experiments:

  - name: lstm_len32_medium_s1
    base: configs/lstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s10
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 10
      train.seed: 1

  - name: lstm_len32_medium_s2
    base: configs/lstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s10
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: false
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 10
      train.seed: 2

  - name: lstm_len32_medium_s3
    base: configs/lstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s10
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: false
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 10
      train.seed: 3

  - name: lstm_len64_medium_s1
    base: configs/lstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s10
      data.max_len: 64
      data.batch_size: 192
      data.gen.enable: false
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 10
      train.seed: 1

  - name: lstm_len64_medium_s2
    base: configs/lstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s10
      data.max_len: 64
      data.batch_size: 192
      data.gen.enable: false
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 10
      train.seed: 2

  - name: lstm_len64_medium_s3
    base: configs/lstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s10
      data.max_len: 64
      data.batch_size: 192
      data.gen.enable: false
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 10
      train.seed: 3
