experiments:

  - name: xlstm_len32_large_s1
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s10
      data.max_len: 32
      data.batch_size: 128
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 10
      train.seed: 1

  - name: xlstm_len32_large_s2
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s10
      data.max_len: 32
      data.batch_size: 128
      data.gen.enable: false
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 10
      train.seed: 2

  - name: xlstm_len32_large_s3
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s10
      data.max_len: 32
      data.batch_size: 128
      data.gen.enable: false
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 10
      train.seed: 3