experiments:

  # ---------- SMALL ----------
  - name: tf_len16_small_s1
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 16
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 1

  - name: tf_len16_small_s2
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 16
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 2

  - name: tf_len16_small_s3
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 16
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 3

  - name: xlstm_len16_small_s1
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 16
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 1

  - name: xlstm_len16_small_s2
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 16
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 2

  - name: xlstm_len16_small_s3
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 16
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 3

  - name: tf_len32_small_s1
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 1

  - name: tf_len32_small_s2
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 2

  - name: tf_len32_small_s3
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 3

  - name: xlstm_len32_small_s1
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 1

  - name: xlstm_len32_small_s2
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 2

  - name: xlstm_len32_small_s3
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c1k_p1k_s10
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 1000
      data.gen.n_products: 1000
      data.gen.seed: 10
      train.seed: 3

  # ---------- MEDIUM ----------
  - name: tf_len32_medium_s1
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 1

  - name: tf_len32_medium_s2
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 2

  - name: tf_len32_medium_s3
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 3

  - name: xlstm_len32_medium_s1
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 1

  - name: xlstm_len32_medium_s2
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 2

  - name: xlstm_len32_medium_s3
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 32
      data.batch_size: 256
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 3

  - name: tf_len64_medium_s1
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 64
      data.batch_size: 192
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 1

  - name: tf_len64_medium_s2
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 64
      data.batch_size: 192
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 2

  - name: tf_len64_medium_s3
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 64
      data.batch_size: 192
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 3

  - name: xlstm_len64_medium_s1
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 64
      data.batch_size: 192
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 1

  - name: xlstm_len64_medium_s2
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 64
      data.batch_size: 192
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 2

  - name: xlstm_len64_medium_s3
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c50k_p20k_s11
      data.max_len: 64
      data.batch_size: 192
      data.gen.enable: true
      data.gen.n_consumers: 50000
      data.gen.n_products: 20000
      data.gen.seed: 11
      train.seed: 3

  # ---------- LARGE ----------
  - name: tf_len32_large_s1
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 32
      data.batch_size: 128
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 1

  - name: tf_len32_large_s2
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 32
      data.batch_size: 128
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 2

  - name: tf_len32_large_s3
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 32
      data.batch_size: 128
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 3

  - name: xlstm_len32_large_s1
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 32
      data.batch_size: 128
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 1

  - name: xlstm_len32_large_s2
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 32
      data.batch_size: 128
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 2

  - name: xlstm_len32_large_s3
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 32
      data.batch_size: 128
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 3

  - name: tf_len64_large_s1
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 64
      data.batch_size: 96
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 1

  - name: tf_len64_large_s2
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 64
      data.batch_size: 96
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 2

  - name: tf_len64_large_s3
    base: configs/transformer_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 64
      data.batch_size: 96
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 3

  - name: xlstm_len64_large_s1
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 64
      data.batch_size: 96
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 1

  - name: xlstm_len64_large_s2
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 64
      data.batch_size: 96
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 2

  - name: xlstm_len64_large_s3
    base: configs/xlstm_base.yaml
    overrides:
      data.csv_dir: data/synth_c250k_p60k_s12
      data.max_len: 64
      data.batch_size: 96
      data.gen.enable: true
      data.gen.n_consumers: 250000
      data.gen.n_products: 60000
      data.gen.seed: 12
      train.seed: 3
